Repository dotnet/docs.ja-jp, pull requests merged in 2018-06, with the labels that each got.

#106 Fix typos
  docs/standard/threading/managed-and-unmanaged-threading-in-windows.md
Labels: Accepted, Linguistic Suggestion

#105 細かな日本語の修正
  docs/framework/tools/signtool-exe.md
Labels: Accepted, Linguistic Suggestion

#104 Update how-to-use-the-aspnet-membership-provider.md
  docs/framework/wcf/feature-details/how-to-use-the-aspnet-membership-provider.md
Labels: Accepted, Linguistic Suggestion

#109 Fix: mistranslation
  docs/visual-basic/programming-guide/program-structure/coding-conventions.md
Labels: Accepted, Linguistic Suggestion

#112 Update unsupported-scenarios.md
  docs/framework/wcf/feature-details/unsupported-scenarios.md
Labels: Accepted, Linguistic Suggestion

#107 Update understanding-protection-level.md
  docs/framework/wcf/understanding-protection-level.md
Labels: Accepted, Linguistic Suggestion

#108 Update how-to-use-a-custom-user-name-and-password-validator.md
  docs/framework/wcf/feature-details/how-to-use-a-custom-user-name-and-password-validator.md
Labels: Accepted, Linguistic Suggestion

#113 Update coding-conventions.md
  docs/visual-basic/programming-guide/program-structure/coding-conventions.md
Labels: Accepted, Linguistic Suggestion

#111 Update naming-conventions.md
  docs/visual-basic/programming-guide/program-structure/naming-conventions.md
Labels: In Progress, Linguistic Suggestion

#119 Update the link for the contribution guide in README.md
  README.md
Labels: Accepted, Source Issue
