Repository dotnet/docs.ja-jp, pull requests merged in 2018-12, with the labels that each got.

#177 fix Japanese
  docs/framework/performance/lazy-initialization.md
Labels: Accepted, Linguistic Suggestion

#182 Fix inline field name
  docs/csharp/language-reference/keywords/class.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#183 Fix typo
  docs/csharp/how-to/compare-strings.md
Labels: Accepted, Linguistic Suggestion

#188 Fix translate
  docs/csharp/language-reference/keywords/enum.md
Labels: Accepted, Linguistic Suggestion

#212 Fix
  docs/standard/net-standard.md
Labels: Accepted, Linguistic Suggestion

#199 Fix miss translate
  docs/csharp/language-reference/operators/toc.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#198 Fix translate
  docs/csharp/language-reference/keywords/namespace-keywords.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#197 Fix miss translate
  docs/csharp/language-reference/operators/namespace-alias-qualifer.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#192 Fix translate
  docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md
Labels: Accepted, Linguistic Suggestion

#189 Fix translate
  docs/csharp/language-reference/keywords/explicit-numeric-conversions-table.md
Labels: Accepted, Linguistic Suggestion

#190 Fix translate
  docs/csharp/language-reference/keywords/fixed-statement.md
Labels: In Progress, Linguistic Suggestion

#191 Fix translate
  docs/csharp/language-reference/keywords/global.md
Labels: In Progress, Linguistic Suggestion

#194 Fix translate 'Verbatim'
  docs/csharp/language-reference/tokens/interpolated.md
Labels: Accepted, Linguistic Suggestion

#196 Fix translate and change link to Japanese forums
  docs/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error.md
Labels: Accepted, Linguistic Suggestion

#202 Fix title to match TOC
  docs/csharp/language-reference/keywords/partial-method.md
Labels: Accepted, Linguistic Suggestion

#204 Fix translate
  docs/csharp/language-reference/keywords/private-protected.md
Labels: Accepted, Linguistic Suggestion

#211 Fix translate
  docs/csharp/language-reference/keywords/volatile.md
Labels: Accepted, Linguistic Suggestion

#206 Fix translate 'Verbatim' and '@-quoted'
  docs/csharp/language-reference/keywords/string.md
Labels: Accepted, Linguistic Suggestion

#210 Fix translate 'verbatim'
  docs/csharp/language-reference/tokens/verbatim.md
Labels: In Progress, Linguistic Suggestion

#226 (& a) #39 が表示されていたため、訳し直した。
  docs/visual-basic/misc/bc31068.md
Labels: Accepted, Linguistic Suggestion

#227 (& A) #39 が表示されていたため、訳し直した。
  docs/visual-basic/misc/bc42328.md
Labels: Accepted, Linguistic Suggestion

#201 Fix translate
  docs/csharp/how-to/parse-strings-using-split.md
  docs/csharp/roslyn-sdk/index.md
Labels: In Progress, Linguistic Suggestion

#214 Fix translate
  docs/standard/library-guidance/cross-platform-targeting.md
Labels: Accepted, Linguistic Suggestion

#218 fix translations
  docs/standard/serverless-architecture/architecture-approaches.md
Labels: Accepted, Linguistic Suggestion

#237 'While' ：'中に' → 'While'
  docs/visual-basic/misc/bc30082.md
Labels: Accepted, Linguistic Suggestion

#229 &#39; が表示されていたため、訳し直した。
  docs/visual-basic/misc/bc31178.md
Labels: Accepted, Linguistic Suggestion

#231 Expected: 予想 → 必要
  docs/visual-basic/misc/bc31179.md
Labels: Accepted, Linguistic Suggestion

#232 '終了' → `End`
  docs/visual-basic/misc/bc30678.md
Labels: Accepted, Linguistic Suggestion

#233 Expected:予想 → 必要です
  docs/visual-basic/misc/bc31167.md
Labels: Accepted, Linguistic Suggestion

#234 終了 → End
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#224 fix translations
  docs/standard/serverless-architecture/serverless-architecture-considerations.md
Labels: Accepted, Linguistic Suggestion

#228 fix translations
  docs/standard/serverless-architecture/serverless-design-examples.md
Labels: In Progress, Linguistic Suggestion

#181 Fix miss-translated
  docs/csharp/language-reference/keywords/async.md
Labels: Accepted, Linguistic Suggestion

#180 Fix 'the containing class'
  docs/csharp/language-reference/keywords/access-modifiers.md
Labels: Accepted, Linguistic Suggestion

#184 Fix translate
  docs/csharp/language-reference/keywords/contextual-keywords.md
Labels: Accepted, Linguistic Suggestion

#186 Update better translate
  docs/csharp/whats-new/csharp-7-3.md
Labels: Accepted, Linguistic Suggestion

#217 Fixed translate of architecture-approaches.md.
  docs/standard/serverless-architecture/architecture-approaches.md
Labels: In Progress, Linguistic Suggestion

#236 fix translations
  docs/standard/serverless-architecture/architecture-approaches.md
Labels: In Progress, Linguistic Suggestion

#239 Fix
  docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md
Labels: Accepted, Linguistic Suggestion

#253 let 束縛 → let バインド
  docs/fsharp/language-reference/members/let-bindings-in-classes.md
Labels: Accepted, Linguistic Suggestion

#252 let 束縛 → let バインド
  docs/fsharp/language-reference/functions/let-bindings.md
Labels: Accepted, Linguistic Suggestion

#251 do 束縛 → do バインド
  docs/fsharp/language-reference/functions/do-bindings.md
Labels: Accepted, Linguistic Suggestion

#250 Bindings:束縛 → バインディング & Remarks → コメント
  docs/fsharp/language-reference/members/explicit-fields-the-val-keyword.md
Labels: Accepted, Linguistic Suggestion

#249 Remarks → コメント
  docs/fsharp/language-reference/pattern-matching.md
Labels: Accepted, Linguistic Suggestion

#247 Bindings:束縛 → バインディング
  docs/fsharp/language-reference/pattern-matching.md
Labels: Accepted, Linguistic Suggestion

#246 Bindings:束縛 → バインディング
  docs/fsharp/language-reference/inheritance.md
Labels: Accepted, Linguistic Suggestion

#245 整数データ型 → Integer データ型
  docs/visual-basic/language-reference/data-types/integer-data-type.md
Labels: Accepted, Linguistic Suggestion

#244 長い形式のデータ型 → Long データ型
  docs/visual-basic/language-reference/data-types/long-data-type.md
Labels: Accepted, Linguistic Suggestion

#243 Bindings:束縛 → バインディング
  docs/fsharp/language-reference/members/events.md
Labels: Accepted, Linguistic Suggestion

#242 Bindings:束縛 → バインディング
  docs/fsharp/language-reference/classes.md
Labels: Accepted, Linguistic Suggestion

#256 <概要 > → <summary>
  docs/visual-basic/language-reference/xmldoc/remarks.md
Labels: Accepted, Linguistic Suggestion

#272 &lt;値&gt; → <value>
  docs/visual-basic/language-reference/xmldoc/value.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#271 &lt;概要&gt; → <summary>
  docs/visual-basic/language-reference/xmldoc/summary.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#268 オーバーロード → Overloads
  docs/visual-basic/language-reference/modifiers/index.md
Labels: Accepted, Linguistic Suggestion

#269 <返します> → <returns>
  docs/visual-basic/language-reference/xmldoc/returns.md
Labels: Accepted, Linguistic Suggestion

#270 &lt;参照してください&gt; → <see>
  docs/visual-basic/language-reference/xmldoc/see.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#267 モジュール → Module
  docs/visual-basic/language-reference/modifiers/module-keyword.md
Labels: Accepted, Linguistic Suggestion

#263 &lt;リスト&gt; → <list>
  docs/visual-basic/language-reference/xmldoc/list.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#264 <アクセス許可> → <permission>
  docs/visual-basic/language-reference/xmldoc/permission.md
Labels: Accepted, Linguistic Suggestion

#262 &lt;含める&gt; → <include>
  docs/visual-basic/language-reference/xmldoc/include.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#261 &lt;例外&gt; → <exception>
  docs/visual-basic/language-reference/xmldoc/exception.md
Labels: Accepted, Linguistic Suggestion, Technical Issue

#265 既定値 → default
  docs/visual-basic/language-reference/modifiers/index.md
Labels: Accepted, Linguistic Suggestion

#200 add description of 'variant'
  docs/csharp/language-reference/keywords/out-generic-modifier.md
Labels: In Progress, Source Issue
