Repository dotnet/docs.ja-jp, pull requests merged in 2019-04, with the labels that each got.

#598 Visual c# → Visual C#
  docs/framework/winforms/how-to-handle-user-input-events-in-windows-forms-controls.md
Labels: In Progress

#603 Visual c# → Visual C#
  docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md
Labels: Accepted

#593 Visual c# → Visual C#
  docs/framework/winforms/how-to-handle-keyboard-input-at-the-form-level.md
Labels: Accepted, Linguistic Suggestion

#606 Typo "Visual c#" → "Visual C#"
  docs/framework/winforms/how-to-modify-keyboard-input-to-a-standard-control.md
Labels: In Progress, Linguistic Suggestion

#600 Visual c# → Visual C#
  docs/framework/winforms/how-to-modify-keyboard-input-to-a-standard-control.md
Labels: Linguistic Suggestion, Partially Accepted

#624 in/out keyword are not recognized correctly.
  docs/csharp/misc/cs0036.md
  docs/csharp/misc/cs0177.md
  docs/csharp/misc/cs0192.md
  docs/csharp/misc/cs0197.md
  docs/csharp/misc/cs0199.md
  docs/csharp/misc/cs0206.md
  docs/csharp/misc/cs0631.md
  docs/csharp/misc/cs0663.md
  docs/csharp/misc/cs1601.md
  docs/csharp/misc/cs1605.md
  docs/csharp/misc/cs1611.md
  docs/csharp/misc/cs1620.md
  docs/csharp/misc/cs1657.md
  docs/visual-basic/language-reference/statements/type-list.md
Labels: Accepted, Linguistic Suggestion

#602 WPF アプリケーションを構築します。→ WPF アプリケーションのビルド
  docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md
Labels: Accepted, Linguistic Suggestion

#630 Fixed "<link>～します。"
  docs/framework/windows-workflow-foundation/data-model.md
  docs/framework/winforms/advanced/about-gdi-managed-code.md
  docs/framework/winforms/creating-a-new-windows-form.md
  docs/visual-basic/programming-guide/language-features/xml/how-to-transform-xml-by-using-linq.md
Labels: Accepted, Linguistic Suggestion

#633 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/how-to-choose-the-printers-attached-to-user-computer-in-windows-forms.md
Labels: In Progress

#635 [チュートリアル。MSBuild の使用] → [チュートリアル: MSBuild の使用]
  docs/visual-basic/reference/command-line-compiler/building-from-the-command-line.md
Labels: Accepted

#607 "標準のコントロールにキーボード入力を変更します。" → "キーボード入力を標準コントロールに変更する"
  docs/framework/winforms/how-to-modify-keyboard-input-to-a-standard-control.md
Labels: Linguistic Suggestion, Partially Accepted

#608 "マウスとキーボード イベントをコードでシミュレートします。" → "マウス イベントとキーボード イベントをコードでシミュレートする"
  docs/framework/winforms/how-to-simulate-mouse-and-keyboard-events-in-code.md
Labels: Linguistic Suggestion, Partially Accepted

#609 "Windows フォーム コントロールでユーザー入力イベントを処理します。" → "Windows フォーム コントロールでユーザー入力…
  docs/framework/winforms/how-to-handle-user-input-events-in-windows-forms-controls.md
Labels: Linguistic Suggestion, Partially Accepted

#615 title: "…プリンターを選択します。" → "…プリンターを選択する"
  docs/framework/winforms/advanced/how-to-choose-the-printers-attached-to-user-computer-in-windows-forms.md
Labels: Accepted, Linguistic Suggestion, Partially Accepted

#616 title: '数回のクリックを区別し、ダブルクリックします。'→'クリックとダブルクリックを識別する'
  docs/framework/winforms/how-to-distinguish-between-clicks-and-double-clicks.md
Labels: Accepted, Linguistic Suggestion

#617 title: 'Windows フォームの境界線を変更します。' → 'Windows フォームの境界線を変更する'
  docs/framework/winforms/how-to-change-the-borders-of-windows-forms.md
Labels: Accepted, Linguistic Suggestion

#618 title: サイズと Windows フォームのスケールを調整します。 → Windows フォームのサイズとスケールを調整する
  docs/framework/winforms/adjusting-the-size-and-scale-of-windows-forms.md
Labels: Accepted, Linguistic Suggestion

#619 方法: Windows フォームの境界線を変更します。 → 方法: Windows フォームの境界線を変更する
  docs/framework/winforms/changing-the-appearance-of-windows-forms.md
Labels: Accepted, Linguistic Suggestion

#620 '方法: コマンドラインから Windows フォーム アプリケーションを作成します。' → '方法: コマンド ラインから Window…
  docs/framework/winforms/how-to-create-a-windows-forms-application-from-the-command-line.md
Labels: Accepted, Linguistic Suggestion

#621 [チュートリアル。WPF でのフォーム コントロールのホストを Windows]→[チュートリアル: WPF での Windows フォー…
  docs/framework/winforms/how-to-create-a-windows-forms-application-from-the-command-line.md
Labels: Accepted, Linguistic Suggestion

#641 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/how-to-complete-windows-forms-print-jobs.md
Labels: In Progress

#623 Fixed mistranslation of "Check out"
  docs/fsharp/get-started/get-started-with-visual-studio-for-mac.md
Labels: Accepted, Linguistic Suggestion

#627 "方法: バインドされたコントロールを作成し、表示されているデータの書式設定" → "方法: バインド コントロールを作成して表示データの…
  docs/framework/winforms/how-to-create-a-bound-control-and-format-the-displayed-data.md
Labels: Accepted, Linguistic Suggestion

#628 '方法: 子テーブルの選択行が正しい位置に保持することを確認します。' → '方法: 子テーブルの選択行が現在位置を保持することを保証する'
  docs/framework/winforms/ensure-the-selected-row-in-a-child-table-correct.md
Labels: Accepted, Linguistic Suggestion

#643 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/how-to-create-standard-windows-forms-print-jobs.md
Labels: Accepted, Linguistic Suggestion

#632 'チュートリアル: デザイン時に Windows フォームで新しい WPF コンテンツを作成します。'→'チュートリアル: デザイン時に …
  docs/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md
Labels: Accepted, Linguistic Suggestion

#644 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/how-to-print-graphics-in-windows-forms.md
Labels: In Progress

#634 [、コマンドラインからビルドする] → [コマンド ラインからのビルド]
  docs/framework/winforms/advanced/how-to-print-a-multi-page-text-file-in-windows-forms.md
Labels: Accepted, Linguistic Suggestion

#653 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/walkthrough-assigning-wpf-content-on-windows-forms-at-design-time.md
Labels: Accepted

#655 fixed inappropriate japanese 静的 → static (toc.yml)
  docs/csharp/language-reference/keywords/toc.yml
Labels: In Progress

#659 fixed inappropriate japanese 追加 → add (toc.yml)
  docs/csharp/language-reference/keywords/toc.yml
Labels: Accepted

#647 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/walkthrough-arranging-wpf-content-on-windows-forms-at-design-time.md
Labels: Accepted, Linguistic Suggestion

#654 fixed inappropriate japanese 種類 → 型 (toc.yml)
  docs/csharp/language-reference/keywords/toc.yml
Labels: Accepted, Linguistic Suggestion

#662 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/walkthrough-styling-wpf-content.md
Labels: Accepted, Linguistic Suggestion
