Repository dotnet/docs.ja-jp, pull requests merged in 2019-05, with the labels that each got.

#664 Typo Visual c# → Visual C#
  docs/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md
Labels: Accepted, Linguistic Suggestion

#672 fixed inappropriate japanese <削除 > → <remove>
  docs/framework/configure-apps/file-schema/runtime/remove-element-for-namedcaches.md
Labels: Accepted, Linguistic Suggestion

#673 fixed inappropriate japanese <追加 > → <add>
  docs/framework/configure-apps/file-schema/runtime/add-element-for-namedcaches.md
Labels: Accepted, Linguistic Suggestion

#674 fixed inappropriate japanese [方法: プログラムで Windows フォームの DataGridView コ…
  docs/framework/winforms/controls/automatically-resize-cells-when-content-changes-in-the-datagrid.md
Labels: Accepted, Linguistic Suggestion

#683 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/disablefusionupdatesfromadmanager-element.md
Labels: In Progress

#689 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/shadowcopyverifybytimestamp-element.md
Labels: In Progress

#690 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/supportportability-element.md
Labels: In Progress

#696 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/etwenable-element.md
Labels: In Progress

#697 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/relativebindforresources-element.md
Labels: In Progress

#680 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/runtime-element.md
Labels: In Progress

#686 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element.md
Labels: In Progress

#694 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/disablecachingbindingfailures-element.md
Labels: In Progress

#679 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/usesmallinternalthreadstacks-element.md
Labels: In Progress

#684 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/enforcefipspolicy-element.md
Labels: In Progress

#685 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/etwenable-element.md
Labels: In Progress

#688 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/relativebindforresources-element.md
Labels: In Progress

#695 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/disablefusionupdatesfromadmanager-element.md
Labels: In Progress

#698 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/supportportability-element.md
Labels: In Progress

#681 Typo
  docs/framework/configure-apps/file-schema/runtime/crst-disablespinwait-element.md
Labels: In Progress

#687 Typo
  docs/framework/configure-apps/file-schema/runtime/gcconcurrent-element.md
Labels: In Progress

#692 Typo
  docs/framework/configure-apps/file-schema/startup/requiredruntime-element.md
Labels: In Progress

#675 fixed inappropriate japanese
  docs/framework/winforms/advanced/how-to-inherit-forms-using-the-inheritance-picker-dialog-box.md
Labels: Accepted, Linguistic Suggestion

#676 Typo Visual c# → Visual C#
  docs/framework/winforms/controls/how-to-provide-a-toolbox-bitmap-for-a-control.md
Labels: Accepted, Linguistic Suggestion

#693 fixed inappropriate japanese "<assemblyBinding > 要素の<ランタイム >" → "<run…
  docs/framework/configure-apps/file-schema/runtime/assemblyidentity-element-for-runtime.md
Labels: Accepted, Linguistic Suggestion

#691 [LOC] Back-Translation ".NETFramework、バージョン = v4.8" → "|4.8|".NETFram…
  docs/framework/configure-apps/file-schema/startup/supportedruntime-element.md
Labels: Accepted, Linguistic Suggestion

#699 [LOC] Back-Translation "<ランタイム > 要素" → "<runtime> 要素"
  docs/framework/configure-apps/file-schema/runtime/uselegacyjit-element.md
Labels: Accepted, Linguistic Suggestion

#701 Typo "。"
  docs/standard/modern-web-apps-azure-architecture/develop-asp-net-core-mvc-apps.md
Labels: In Progress

#702 XML element name should not be translated
  docs/core/tools/csproj.md
Labels: In Progress

#704 Back-Translation "ストア" -> "store"
  docs/core/tools/index.md
Labels: In Progress

#703 Retranslate freezable objects overview
  docs/framework/wpf/advanced/freezable-objects-overview.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue
