Repository dotnet/docs.ja-jp, pull requests merged in 2019-10, with the labels that each got.

#820 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/gcserver-element.md
Labels: Accepted

#823 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/legacycorruptedstateexceptionspolicy-element.md
Labels: Accepted

#821 [LOC] Back-Translation "新しい演算子"→"new 演算子"
  docs/fsharp/language-reference/operator-overloading.md
Labels: Accepted, Linguistic Suggestion

#824 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/legacyimpersonationpolicy-element.md
Labels: Accepted

#825 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/loadfromremotesources-element.md
Labels: Linguistic Suggestion, Partially Accepted

#831 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/netfx40-pinvokestackresilience-element.md
Labels: Accepted

#830 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/netfx40-legacysecuritypolicy-element.md
Labels: Accepted

#834 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/relativebindforresources-element.md
Labels: Accepted

#833 [LOC] Back-Translation "<ランタイム >"→"<runtime>
  docs/framework/configure-apps/file-schema/runtime/prefercominsteadofmanagedremoting-element.md
Labels: Accepted

#832 [LOC] Back-Translation "<ランタイム >"→"<runtime>
  docs/framework/configure-apps/file-schema/runtime/netfx45-cultureawarecomparergethashcode-longstrings-element.md
Labels: Accepted

#835 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/shadowcopyverifybytimestamp-element.md
Labels: Accepted

#839 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/thread-useallcpugroups-element.md
Labels: Accepted

#840 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/runtime-element.md
Labels: Accepted

#836 Fix translate of clause md
  docs/visual-basic/language-reference/statements/of-clause.md
Labels: Accepted, Linguistic Suggestion

#837 fix: translates to natural Japanese from machine translation.
  docs/visual-basic/programming-guide/com-interop/how-to-call-windows-apis.md
Labels: Accepted, Linguistic Suggestion

#838 fix: translates to natural Japanese from machine translates.
  docs/visual-basic/programming-guide/com-interop/how-to-call-a-windows-function-that-takes-unsigned-types.md
Labels: Accepted, Linguistic Suggestion

#846 Update get-started-with-visual-studio-for-mac.md
  docs/fsharp/get-started/get-started-with-visual-studio-for-mac.md
Labels: Accepted, Linguistic Suggestion

#849 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/throwunobservedtaskexceptions-element.md
Labels: Accepted

#844 Update install-fsharp.md
  docs/fsharp/get-started/install-fsharp.md
Labels: Accepted, Linguistic Suggestion

#845 Update get-started-visual-studio.md
  docs/fsharp/get-started/get-started-visual-studio.md
Labels: Accepted, Linguistic Suggestion

#848 fix: mistranslation of title.
  docs/visual-basic/programming-guide/language-features/data-types/type-characters.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#847 Fix translate special characters in code md
  docs/visual-basic/programming-guide/program-structure/special-characters-in-code.md
Labels: Accepted, Linguistic Suggestion

#851 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/timespan-legacyformatmode-element.md
Labels: In Progress, Linguistic Suggestion

#853 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/uselegacyjit-element.md
Labels: Accepted, Linguistic Suggestion

#850 Update get-started-vscode.md
  docs/fsharp/get-started/get-started-vscode.md
Labels: Accepted, Linguistic Suggestion

#854 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/userandomizedstringhashalgorithm-element.md
Labels: In Progress

#852 getting started with VS code, VS, VS for Macの翻訳内容を見直し
  docs/fsharp/get-started/get-started-visual-studio.md
  docs/fsharp/get-started/get-started-vscode.md
  docs/fsharp/get-started/get-started-with-visual-studio-for-mac.md
  docs/fsharp/introduction-to-functional-programming/index.md
  docs/fsharp/tour.md
  docs/fsharp/tutorials/asynchronous-and-concurrent-programming/async.md
Labels: Accepted, Linguistic Suggestion

#856 語順を変更することで自然な日本語に修正
  docs/framework/data/adonet/sql-server-connection-pooling.md
Labels: Accepted, Linguistic Suggestion

#859 Update in-generic-modifier.md
  docs/csharp/language-reference/keywords/in-generic-modifier.md
Labels: In Progress

#857 パターン名の不完全な翻訳を修正
  docs/standard/design-guidelines/exceptions-and-performance.md
Labels: Accepted, Linguistic Suggestion
