Repository dotnet/docs.ja-jp, pull requests merged in 2019-11, with the labels that each got.

#858 datagrid.mdの不完全な翻訳を修正
  docs/framework/wpf/controls/datagrid.md
Labels: Accepted, Linguistic Suggestion

#861 fixed inappropriate japanese: 読点の位置や助詞（て、に、を、は）を修正
  docs/visual-basic/language-reference/nothing.md
Labels: Accepted, Linguistic Suggestion

#863 updated intro-to-functional-programming and async-and-conccrent-programming of docs/fsharp
  docs/fsharp/introduction-to-functional-programming/first-class-functions.md
  docs/fsharp/introduction-to-functional-programming/index.md
  docs/fsharp/tutorials/asynchronous-and-concurrent-programming/async.md
  docs/fsharp/tutorials/type-providers/creating-a-type-provider.md
  docs/fsharp/tutorials/type-providers/index.md
Labels: Linguistic Suggestion, Partially Accepted, Source Issue, Technical Issue

#865 Fixed mistranslating, 'Right' is simply reverse ordered 'Left'.
  docs/fsharp/language-reference/symbol-and-operator-reference/index.md
Labels: Accepted, Linguistic Suggestion

#868 [LOC] Back-Translation "<ランタイム >"→"<runtime>"
  docs/framework/configure-apps/file-schema/runtime/runtime-element.md
Labels: Accepted, Linguistic Suggestion

#867 [LOC]Back-Translation "のキャッシュ"→"system.runtime.caching"
  docs/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings.md
Labels: Accepted

#866 [LOC]fixed inappropriate japanese "<の>"→"<system.runtime.caching>"
  docs/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings.md
Labels: Accepted, Linguistic Suggestion

#869 Typo "TRUE"→"true"
  docs/framework/configure-apps/file-schema/runtime/usesmallinternalthreadstacks-element.md
Labels: Accepted

#870 Typo "\<memoryCache >"→"\<memoryCache>"
  docs/framework/configure-apps/file-schema/runtime/memorycache-element-cache-settings.md
Labels: Accepted

#872 [LOC] Back-Translation "<プローブ >"→"<probing>"
  docs/framework/configure-apps/file-schema/runtime/probing-element.md
Labels: Accepted

#879 [LOC]Fixd "@ no__t-1 <mscorlib > "→"<mscorlib>"
  docs/framework/configure-apps/file-schema/cryptography/index.md
Labels: In Progress

#880 [LOC]Fixd "' @No__t-1genericproceduresignature > '"→"' \<genericproce…
  docs/visual-basic/misc/bc32051.md
Labels: In Progress

#878 [LOC]Fix "@ no__t-1 @ no__t @ no__t-3 <applicationPool > "→"<applicat…
  docs/framework/configure-apps/file-schema/web/index.md
Labels: In Progress

#877 [LOC]fixed inappropriate japanese "\<構成 > 要素" → "\<configuration> 要素"
  docs/framework/configure-apps/file-schema/configuration-element.md
Labels: Accepted, Linguistic Suggestion

#881 [LOC]fixed inappropriate japanese "<[**ソース**]" → "[**\<sources>**]"
  docs/framework/configure-apps/file-schema/trace-debug/source-element.md
Labels: Accepted

#882 [LOC]Fixed inappropriate japanese "**\<の >**"→"**\<system.diagnostics…
  docs/framework/configure-apps/file-schema/trace-debug/system-diagnostics-element.md
Labels: Accepted

#883 [LOC] Back-Translation "ドーナツ"→"OID"
  docs/framework/configure-apps/file-schema/cryptography/oidentry-element.md
Labels: In Progress

#876 [LOC]fixed inappropriate japanese "\<構成の appSettings > 要素を \<>" → "\<…
  docs/framework/configure-apps/file-schema/appsettings/appsettings-element-for-configuration.md
Labels: Accepted, Linguistic Suggestion

#886 [LOC] Back-Translation "\<**クリア >**"→"\<**clear>**"
  docs/framework/configure-apps/file-schema/network/clear-element-for-bypasslist-network-settings.md
Labels: Accepted

#885 [LOC]fixed inappropriate japanese "要素を削除"→"<remove> 要素"
  docs/framework/configure-apps/file-schema/network/remove-element-for-bypasslist-network-settings.md
Labels: Accepted

#873 [LOC]fixed inappropriate japanese "\<appSettings > の > 要素を追加 \<" → "<…
  docs/framework/configure-apps/file-schema/appsettings/add-element-for-appsettings.md
Labels: Accepted, Linguistic Suggestion

#884 [LOC]fixed inappropriate japanese "要素を追加"→"<add> 要素"
  docs/framework/configure-apps/file-schema/network/add-element-for-bypasslist-network-settings.md
Labels: Accepted, Linguistic Suggestion

#875 [LOC]fixed inappropriate japanese "\<appSettings > の > 要素を削除 \<" → "<…
  docs/framework/configure-apps/file-schema/appsettings/remove-element-for-appsettings.md
Labels: Accepted, Linguistic Suggestion

#888 [LOC]Back-Translation "<**プロキシ >**"→"**\<proxy>**"
  docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md
Labels: Accepted

#887 [LOC]Back-Translation "<**モジュール >**"→"**\<module>**"
  docs/framework/configure-apps/file-schema/network/module-element-network-settings.md
Labels: Accepted

#893 [LOC] Back-Translation "[ **\<スタートアップ >** ]"→"[**\<startup>**]"
  docs/framework/configure-apps/file-schema/startup/requiredruntime-element.md
Labels: Accepted

#892 [LOC] Back-Translation "[ \<プローブ >]"→"[\<probing>]"
  docs/framework/configure-apps/specify-assembly-location.md
Labels: Accepted

#889 Typo "**defaultProxy\<**"→"**\<defaultProxy>**"
  docs/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.md
Labels: Accepted

#891 Typo "[ **\<runtime>** ]"→"[**\<runtime>**]"
  docs/framework/configure-apps/file-schema/runtime/probing-element.md
Labels: Accepted

#890 [LOC] Back-Translation "\<**追加 >**"→"**\<add>**"
  docs/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings.md
Labels: In Progress, Linguistic Suggestion, Technical Issue
