Repository dotnet/docs.ja-jp, pull requests merged in 2019-01, with the labels that each got.

#277 クラス → Class
  docs/visual-basic/language-reference/statements/a-e-statements.md
Labels: Accepted, Linguistic Suggestion

#278 操作を実行しています.ループ → Do...Loop
  docs/visual-basic/language-reference/statements/a-e-statements.md
Labels: Linguistic Suggestion

#279 End&lt;キーワード&gt; → End<keyword>
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#281 終了 → Exit
  docs/visual-basic/language-reference/statements/a-e-statements.md
Labels: Accepted, Linguistic Suggestion

#276 WHERE 句 → Where 句
  docs/visual-basic/language-reference/queries/index.md
Labels: Accepted, Linguistic Suggestion

#282 など → Like
  docs/visual-basic/language-reference/keywords/operators-summary.md
Labels: Accepted, Linguistic Suggestion

#286 開発 (アプリケーションを) → Visual Basic でのアプリケーションの開発
  docs/toc.md
Labels: Accepted, Linguistic Suggestion

#287 プライベート、 → Private,
  docs/visual-basic/language-reference/keywords/arrays-summary.md
Labels: Accepted, Linguistic Suggestion

#290 整数データ型 → Integer データ型
  docs/toc.md
Labels: Accepted

#291 モジュール → Module
  docs/visual-basic/language-reference/statements/f-p-statements.md
Labels: Accepted, Linguistic Suggestion

#293 オプション&lt;キーワード&gt; → Option<キーワード>
  docs/visual-basic/language-reference/statements/option-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#294 このオプションを選択するとしてください.場合 → Select...Case
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#296 お試しください.キャッチしてください.最終的に → Try...Catch...Finally
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#299 Aブール式の値 → ブール式の値
  docs/visual-basic/programming-guide/language-features/operators-and-expressions/boolean-expressions.md
Labels: Accepted, Linguistic Suggestion

#300 ブール型 (Boolean)、ブール データ型 → Boolean データ型
  docs/visual-basic/language-reference/data-types/boolean-data-type.md
Labels: Accepted, Linguistic Suggestion

#303 しています.Next ステートメント → For...Next ステートメント
  docs/visual-basic/language-reference/statements/as-clause.md
Labels: Accepted, Linguistic Suggestion

#306 既定値 → Default
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#314 オーバーロード → Overload
  docs/toc.md
Labels: Accepted, Linguistic Suggestion

#315 モジュール → Module
  docs/toc.md
Labels: Accepted, Linguistic Suggestion

#320 ブール、バイト、 ～ → Boolean, Byte, ～
  docs/visual-basic/language-reference/keywords/data-types-summary.md
Labels: Accepted, Linguistic Suggestion

#321 &lt;para&gt; → <para> & Remarks → コメント
  docs/visual-basic/language-reference/xmldoc/para.md
Labels: Accepted, Linguistic Suggestion

#324 "Use the <code> tag to indicate～" translated
  docs/visual-basic/language-reference/xmldoc/code.md
Labels: Accepted, Linguistic Suggestion

#327 &lt;例&gt; → <example> & Remarks → コメント
  docs/visual-basic/language-reference/xmldoc/example.md
Labels: Accepted, Linguistic Suggestion

#274 Translated Input overview
  docs/framework/wpf/advanced/input-overview.md
Labels: Accepted, Linguistic Suggestion

#329 'ElseIf' の前には、対応する → '#ElseIf' の前には、対応する
  docs/toc.md
Labels: Accepted, Linguistic Suggestion

#333 お試しください.Catch ステートメント → Try…Catchステートメント
  docs/visual-basic/language-reference/statements/try-catch-finally-statement.md
Labels: Accepted, Linguistic Suggestion

#332 title: '～必要です'" → '～が必要です"
  docs/visual-basic/language-reference/error-messages/elseif-must-be-preceded-by-a-matching-if-or-elseif.md
Labels: In Progress, Linguistic Suggestion

#331 language データ型 → Integer データ型
  docs/visual-basic/programming-guide/language-features/data-types/numeric-data-types.md
Labels: Accepted, In Progress

#297 しばらくしています.中に終了 → While...End While
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#295 構造体 → Structure
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#280 エラー → Error
  docs/visual-basic/language-reference/statements/a-e-statements.md
Labels: Accepted, Linguistic Suggestion

#283 は → Is
  docs/visual-basic/language-reference/keywords/operators-summary.md
Labels: Accepted, Linguistic Suggestion

#284 いない、 → Not,
  docs/visual-basic/language-reference/keywords/operators-summary.md
Labels: Accepted, Linguistic Suggestion

#285 または → Or,
  docs/visual-basic/language-reference/keywords/operators-summary.md
Labels: Accepted, Linguistic Suggestion

#288 パブリック、 → Public,
  docs/visual-basic/language-reference/keywords/arrays-summary.md
Labels: Accepted, Linguistic Suggestion

#289 消去、→ Erase,
  docs/visual-basic/language-reference/keywords/arrays-summary.md
Labels: Accepted, Linguistic Suggestion

#298 しています.を終わる → With...End With
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#304 各しています.Next ステートメント → For Each...Next ステートメント
  docs/visual-basic/language-reference/statements/as-clause.md
Labels: Accepted, Linguistic Suggestion

#326 <c タグ → <c> タグ
  docs/visual-basic/language-reference/xmldoc/code.md
Labels: Accepted, Linguistic Suggestion

#307 エラー → Error
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#308 次へ → Next
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#322 <概要>、<解説>、<返します>→<summary>, <remarks>, <returns>
  docs/visual-basic/language-reference/xmldoc/para.md
Labels: Accepted, Linguistic Suggestion

#310 モジュール → Module
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#311 オブジェクト → Object
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#312 オプション&lt;キーワード&gt;,オプション<キーワード> → Option <キーワード>
  docs/visual-basic/language-reference/statements/option-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#313 オプション → Option
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#316 目的 → To
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#319 [テキスト] → Text
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#318 カスタム → Custom
  docs/visual-basic/language-reference/keywords/index.md
Labels: Accepted, Linguistic Suggestion

#309 オブジェクトのデータ型, Object Data Type → Object データ型
  docs/visual-basic/language-reference/data-types/object-data-type.md
Labels: In Progress, Linguistic Suggestion

#382 明示的なフィールド。valキーワード → 明示的なフィールド:Val キーワード
  docs/fsharp/language-reference/inheritance.md
Labels: Accepted

#380 再開 → Resume
  docs/visual-basic/language-reference/keywords/errors-summary.md
Labels: Accepted

#348 letとdoのバインディング → letとdoバインド
  docs/fsharp/language-reference/classes.md
Labels: Accepted, Linguistic Suggestion

#370 1 つのデータ型 → Single データ型
  docs/visual-basic/programming-guide/language-features/data-types/troubleshooting-data-types.md
Labels: Accepted, Linguistic Suggestion

#376 文字列データ型 → String データ型
  docs/visual-basic/programming-guide/language-features/data-types/troubleshooting-data-types.md
Labels: Accepted, Linguistic Suggestion

#375 ブール型のデータ型 → Boolean データ型
  docs/visual-basic/programming-guide/language-features/data-types/troubleshooting-data-types.md
Labels: Accepted, Linguistic Suggestion

#377 文字列値は～変換が危険な。 → 文字列値は～変換は非常に危険です。
  docs/visual-basic/programming-guide/language-features/data-types/troubleshooting-data-types.md
Labels: Accepted, Linguistic Suggestion

#385 Aメンバー変数は → メンバー変数は
  docs/visual-basic/programming-guide/language-features/variables/variable-declaration.md
Labels: Accepted, Linguistic Suggestion

#402 保護されたプライベート → Private Protected
  docs/visual-basic/language-reference/modifiers/friend.md
Labels: Accepted, Linguistic Suggestion

#404 保護されたフレンド → Protected Friend
  docs/visual-basic/language-reference/modifiers/protected-friend.md
Labels: Accepted, Linguistic Suggestion

#400 する方法: 作成の署名～ → 方法: 署名のない～
  docs/visual-basic/programming-guide/concepts/assemblies-gac/friend-assemblies.md
Labels: In Progress, Linguistic Suggestion

#350 let bindings: let バインディング → let バインド
  docs/fsharp/language-reference/inheritance.md
Labels: Accepted, Linguistic Suggestion

#349 Bindings:バインディング → バインド
  docs/fsharp/language-reference/members/events.md
Labels: In Progress, Linguistic Suggestion

#368 &#39;&lt;membername&gt; &#39;型～ → '<membername>'～
  docs/visual-basic/language-reference/error-messages/membername-cannot-expose-type-typename-outside-the-project.md
Labels: In Progress, Linguistic Suggestion

#369 組→ タプル
  docs/visual-basic/programming-guide/language-features/data-types/tuples.md
Labels: Accepted, Linguistic Suggestion

#411 c# → C#
  docs/framework/debug-trace-profile/making-an-image-easier-to-debug.md
Labels: Accepted, Linguistic Suggestion

#419 プライベート保護 → Private Protected
  docs/visual-basic/language-reference/modifiers/protected.md
Labels: Accepted, Linguistic Suggestion

#417 プライベート保護 → Private Protected
  docs/visual-basic/language-reference/modifiers/friend.md
Labels: Accepted, Linguistic Suggestion

#413 c# → C# & Api → API
  docs/visual-basic/programming-guide/concepts/async/index.md
Labels: Accepted, Linguistic Suggestion

#412 c# → C# & Api → API
  docs/visual-basic/programming-guide/concepts/async/index.md
Labels: Accepted, Linguistic Suggestion

#410 Visual Basic 2017 組 → Visual Basic 2017 のタプル
  docs/fsharp/language-reference/tuples.md
Labels: Accepted, Linguistic Suggestion

#428 お試しください.キャッチしてください.Finally ステートメント → Try...Catch...Finally ステートメント
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#431 お試しくださいブロック → Tryブロック
  docs/visual-basic/language-reference/statements/try-catch-finally-statement.md
Labels: Accepted, Linguistic Suggestion

#405 手順 → プロシージャ
  docs/visual-basic/language-reference/modifiers/friend.md
Labels: Accepted, Linguistic Suggestion

#408 Aタプル名前のないが～ → タプルは、名前のない
  docs/fsharp/language-reference/tuples.md
Labels: Accepted, Linguistic Suggestion

#414 お試しください.キャッチ → Try...Catch
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#426 (などパブリックまたはプライベート) → (PublicまたはPrivateなど)
  docs/visual-basic/programming-guide/language-features/variables/variable-declaration.md
Labels: Accepted, Linguistic Suggestion

#423 Azure Queue storage の概要します。→ Azure Queue Storage の概要
  docs/fsharp/using-fsharp-on-azure/queue-storage.md
Labels: Accepted, Linguistic Suggestion

#422 Azure File storage の概要します。→ Azure File Storage の概要
  docs/fsharp/using-fsharp-on-azure/file-storage.md
Labels: Accepted, Linguistic Suggestion

#421 Azure Blob storage の概要します。→ Azure Blob Storage の概要
  docs/fsharp/using-fsharp-on-azure/blob-storage.md
Labels: Accepted, Linguistic Suggestion

#437 &lt;defaultProxy&gt;要素 → <defaultProxy>要素
  docs/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#436 &lt;プロキシ&gt;要素 → <proxy> 要素
  docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#434 &lt;bypasslist&gt;要素 → <bypasslist>要素
  docs/framework/configure-apps/file-schema/network/bypasslist-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#257 '&lt;「解説」&gt; → <remarks>
  docs/visual-basic/language-reference/xmldoc/remarks.md
Labels: Accepted, Linguistic Suggestion

#451 &lt;ネットワーク&gt;要素 (ネットワーク設定) → <network> 要素 (ネットワーク設定)
  docs/framework/configure-apps/file-schema/network/network-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#450 &lt;削除&gt;bypasslist の要素 → bypasslist の <remove> 要素
  docs/framework/configure-apps/file-schema/network/remove-element-for-bypasslist-network-settings.md
Labels: Accepted, Linguistic Suggestion

#449 &lt;オフ&gt;bypasslist の要素 → bypasslist の <clear> 要素
  docs/framework/configure-apps/file-schema/network/clear-element-for-bypasslist-network-settings.md
Labels: Accepted, Linguistic Suggestion

#448 &lt;追加&gt;bypasslist の要素 → bypasslist の <add> 要素
  docs/framework/configure-apps/file-schema/network/add-element-for-bypasslist-network-settings.md
Labels: Accepted, Linguistic Suggestion

#447 &lt;削除&gt;connectionManagement の要素 → connectionManagement の <remove> 要素
  docs/framework/configure-apps/file-schema/network/remove-element-for-connectionmanagement-network-settings.md
Labels: Accepted, Linguistic Suggestion

#446 &lt;オフ&gt;connectionManagement の要素 → connectionManagement の <clear> 要素
  docs/framework/configure-apps/file-schema/network/clear-element-for-connectionmanagement-network-settings.md
Labels: Accepted, Linguistic Suggestion

#445 &lt;追加&gt;connectionManagement の要素 → connectionManagement の <add> 要素
  docs/framework/configure-apps/file-schema/network/add-element-for-connectionmanagement-network-settings.md
Labels: Accepted, Linguistic Suggestion

#444 &lt;connectionManagement&gt;要素 → <connectionManagement>要素
  docs/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#443 &lt;オフ&gt;authenticationModules の要素 → authenticationModules の <clear> 要素
  docs/framework/configure-apps/file-schema/network/clear-element-for-authenticationmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#442 &lt;削除&gt;authenticationModules の要素 → authenticationModules の <remove…
  docs/framework/configure-apps/file-schema/network/remove-element-for-authenticationmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#441 &lt;追加&gt;authenticationModules の要素 → authenticationModules の <add> 要素
  docs/framework/configure-apps/file-schema/network/add-element-for-authenticationmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#440 &lt;authenticationModules&gt;要素 → <authenticationModules>要素
  docs/framework/configure-apps/file-schema/network/authenticationmodules-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#454 &lt;オフ&gt;schemeSettings (Uri 設定) の要素 → schemeSettings の <clear> 要素 (…
  docs/framework/configure-apps/file-schema/network/clear-element-for-schemesettings-uri-settings.md
Labels: Accepted, Linguistic Suggestion

#456 &lt;ソケット&gt;要素 (ネットワーク設定) → <socket> 要素 (ネットワーク設定)
  docs/framework/configure-apps/file-schema/network/socket-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#457 &lt;httpListener&gt;要素 (ネットワーク設定) → <httpListener>要素 (ネットワーク設定)
  docs/framework/configure-apps/file-schema/network/httplistener-element-network-settings.md
Labels: Accepted, Linguistic Suggestion

#466 詳しくは、「Try...Catch...Finally ステートメント」をご覧ください。→ 詳細については、Try...Catch...F…
  docs/visual-basic/programming-guide/language-features/control-flow/decision-structures.md
Labels: Accepted, Linguistic Suggestion

#468 参照してください操作を行います...ステートメントをループです。→ Do ... Loopステートメントを参照してください。
  docs/visual-basic/programming-guide/language-features/control-flow/loop-structures.md
Labels: Accepted, Linguistic Suggestion

#458 使用しています.構築を使用して終了 → Using...End Using の構築
  docs/visual-basic/programming-guide/language-features/control-flow/other-control-structures.md
Labels: Accepted, Linguistic Suggestion

#473 &lt;追加&gt;webRequestModules (ネットワーク設定) の要素 → webRequestModules の <add…
  docs/framework/configure-apps/file-schema/network/add-element-for-webrequestmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#476 &lt;構成&gt;要素 → <configuration> 要素
  docs/framework/configure-apps/file-schema/configuration-element.md
Labels: Accepted, Linguistic Suggestion

#474 &lt;削除&gt;webRequestModules (ネットワーク設定) の要素 → webRequestModules の <rem…
  docs/framework/configure-apps/file-schema/network/remove-element-for-webrequestmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#475 &lt;オフ&gt;webRequestModules (ネットワーク設定) の要素 → webRequestModules の <cle…
  docs/framework/configure-apps/file-schema/network/clear-element-for-webrequestmodules-network-settings.md
Labels: Accepted, Linguistic Suggestion

#477 &lt;Uri&gt;要素 (Uri 設定) → <Uri>要素 (Uri 設定)
  docs/framework/configure-apps/file-schema/network/uri-element-uri-settings.md
Labels: Accepted, Linguistic Suggestion

#480 &lt;schemeSettings&gt;要素 → <schemeSettings>要素
  docs/framework/configure-apps/file-schema/network/schemesettings-element-uri-settings.md
Labels: Accepted, Linguistic Suggestion

#479 &lt;iriParsing&gt;要素 → <iriParsing>要素
  docs/framework/configure-apps/file-schema/network/iriparsing-element-uri-settings.md
Labels: Accepted, Linguistic Suggestion

#478 &lt;idn&gt;要素 → <idn>要素
  docs/framework/configure-apps/file-schema/network/idn-element-uri-settings.md
Labels: Accepted, Linguistic Suggestion

#260 &lt;例&gt; → <example>
  docs/visual-basic/language-reference/xmldoc/example.md
Labels: Accepted, Technical Issue

#497 場合.そうしたら...Else ステートメント → If...Then...Else ステートメント
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#496 関数ステートメント → Function ステートメント
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#495 クラス ステートメント → Class ステートメント
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#494 End&lt;keyword&gt;ステートメント → End<keyword>
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#501 . operator → . 演算子
  docs/csharp/language-reference/operators/member-access-operator.md
Labels: Accepted, Linguistic Suggestion

#499 モジュール ステートメント → Module ステートメント
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: Accepted, Linguistic Suggestion

#504 title:'.' は、基本クラス → '<interfacename>.<membername>' は、基本クラス
  docs/visual-basic/language-reference/error-messages/interfacename-membername-is-already-implemented-by-the-base-class.md
Labels: Accepted, Linguistic Suggestion

#493 Fix translate
  docs/framework/wpf/advanced/wpf-architecture.md
Labels: Accepted, Linguistic Suggestion

#506 '<キーワード >' は、 → '<keyword>' は、
  docs/visual-basic/language-reference/error-messages/keyword-is-valid-only-within-an-instance-method.md
Labels: Accepted, Linguistic Suggestion
