Repository dotnet/docs.ja-jp, pull requests merged in 2019-07, with the labels that each got.

#711 Fix "For Each" mistranslation
  docs/visual-basic/language-reference/modifiers/iterator.md
  docs/visual-basic/language-reference/statements/for-next-statement.md
  docs/visual-basic/language-reference/statements/function-statement.md
  docs/visual-basic/language-reference/statements/option-strict-statement.md
  docs/visual-basic/language-reference/statements/try-catch-finally-statement.md
  docs/visual-basic/language-reference/statements/yield-statement.md
  docs/visual-basic/programming-guide/concepts/collections.md
  docs/visual-basic/programming-guide/concepts/iterators.md
  docs/visual-basic/programming-guide/language-features/arrays/index.md
  docs/visual-basic/programming-guide/language-features/control-flow/loop-structures.md
  docs/visual-basic/programming-guide/language-features/data-types/troubleshooting-data-types.md
  docs/visual-basic/programming-guide/language-features/data-types/widening-and-narrowing-conversions.md
  docs/visual-basic/programming-guide/language-features/objects-and-classes/index.md
  docs/visual-basic/programming-guide/language-features/statements.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#712 💡自然な日本語となるように再翻訳
  docs/fsharp/get-started/index.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#715 不要な記号の削除
  docs/machine-learning/toc.yml
Labels: Accepted

#716 fix translations
  docs/machine-learning/how-to-guides/serve-model-web-api-ml-net.md
Labels: Accepted, Linguistic Suggestion

#719 Update toc.yml "References to Declared Elements"→"宣言された要素の参照"
  docs/visual-basic/programming-guide/language-features/declared-elements/toc.yml
Labels: Accepted, Linguistic Suggestion

#723 fix "「こんにちは, world!」"→""Hello, world!""
  docs/framework/wcf/samples/loosely-typed-extensions-sample.md
Labels: Accepted

#717 fix "「こんにちは, world!」"→"Hello, world!"
  docs/visual-basic/language-reference/typographic-and-code-conventions.md
Labels: Accepted, Linguistic Suggestion

#718 fix "パス名です。"→"修飾"
  docs/visual-basic/language-reference/statements/module-statement.md
Labels: Accepted, Linguistic Suggestion

#722 fix "「こんにちは, world!」"→""Hello, world!""
  docs/framework/wcf/feature-details/how-to-access-a-service-from-a-workflow-application.md
Labels: Accepted, Linguistic Suggestion

#726 fix "「こんにちは, world」"→""Hello, world""
  docs/visual-basic/programming-guide/program-structure/program-structure-and-code-conventions.md
Labels: Accepted

#720 Update links of AspNetCore.App in packages.md
  docs/core/packages.md
Labels: Accepted, Linguistic Suggestion

#727 fix "ull 合体演算子"→"Null 合体演算子"
  docs/csharp/language-reference/keywords/throw.md
Labels: Accepted

#724 fix ".NET 標準"→".NET standards"
  docs/core/about.md
Labels: Accepted, Linguistic Suggestion

#725 fix "「こんにちは, world!」"→""Hello, world!""
  docs/visual-basic/programming-guide/program-structure/program-structure-and-code-conventions.md
Labels: Accepted, Linguistic Suggestion
