Repository dotnet/docs.ja-jp, pull requests merged in 2019-03, with the labels that each got.

#572 '<typename >' はデリゲート型です。 → '<typename>' はデリゲート型です。
  docs/visual-basic/language-reference/error-messages/typename-is-a-delegate-type.md
Labels: Accepted, Linguistic Suggestion

#571 '<typename >' は型であり、式として使用することはできません → '<typename>' は型であるため、式として使用するこ…
  docs/visual-basic/language-reference/error-messages/typename-is-a-type-and-cannot-be-used-as-an-expression.md
Labels: Linguistic Suggestion, Partially Accepted

#573 A`New`デリゲート クラスのインスタンスを作成する句は、 → デリゲート クラスのインスタンスを作成する`New`句で、
  docs/visual-basic/language-reference/error-messages/typename-is-a-delegate-type.md
Labels: Accepted, Linguistic Suggestion

#574 1 つだけを指定するAddressOf → 単一の AddressOf 式しか指定できません。
  docs/visual-basic/language-reference/error-messages/typename-is-a-delegate-type.md
Labels: Accepted, Linguistic Suggestion

#575 1 つ以上の引数を渡すまたは有効なではない場合は → このエラーは、デリゲート コンストラクタへ引数を 1 つも渡していない場合、
  docs/visual-basic/language-reference/error-messages/typename-is-a-delegate-type.md
Labels: Linguistic Suggestion, Partially Accepted

#576 1 つを使用して、`AddressOf`に → 単一の AddressOf 式を使用します。
  docs/visual-basic/language-reference/error-messages/typename-is-a-delegate-type.md
Labels: In Progress, Linguistic Suggestion

#581 fix #577
  docs/csharp/language-reference/keywords/in-parameter-modifier.md
Labels: Accepted, Linguistic Suggestion

#579 '<typename >' はクラス型であり、 → '<typename>' はクラス型であるため、
  docs/visual-basic/misc/bc30109.md
Labels: Linguistic Suggestion, Partially Accepted

#578 '<typename >' 名前空間であり、 → '<typename>' は名前空間であり、
  docs/visual-basic/misc/bc30112.md
Labels: Linguistic Suggestion, Partially Accepted

#580 '<typename>' で公開されている別の型と同じ名前を持つ、'My' グループ → '<typename>' は 'My' グループ…
  docs/visual-basic/misc/bc36015.md
Labels: Linguistic Suggestion, Partially Accepted

#585 Visual c# → Visual C#
  docs/framework/windows-workflow-foundation/control-flow-activities-in-wf.md
Labels: Accepted, Linguistic Suggestion

#587 意味のわかる日本語に修正。
  docs/standard/design-guidelines/general-naming-conventions.md
Labels: Linguistic Suggestion, Partially Accepted

#590 Visual c# → Visual C#
  docs/framework/winforms/how-to-distinguish-between-clicks-and-double-clicks.md
Labels: Accepted, In Progress

#588 Choosing between class and struct
  docs/standard/design-guidelines/choosing-between-class-and-struct.md
Labels: Linguistic Suggestion, Partially Accepted

#589 Abstract class
  docs/standard/design-guidelines/abstract-class.md
Labels: Linguistic Suggestion, Partially Accepted
